on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Install Buf
      run: make install-buf
      
    # - name: Run check
    #   run: make check
      
    # - name: Run distcheck
    #   run: make distcheck