on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    # - name: Install dependencies
    #   run: make install-deps

    - name: Install Buf
      run: ./install_buf.sh
      
    # - name: Run check
    #   run: make check
      
    # - name: Run distcheck
    #   run: make distcheck